    cdef AsmOperand upper_bound_sd = generate_double_static_constant_operand(9223372036854775808.0, 8)
    cdef AsmOperand src = generate_operand(node.src)
    cdef AssemblyType assembly_type_sd = BackendDouble()
    cdef AsmCondCode cond_code_ae = AsmAE()
    cdef TIdentifier target_out_of_range = represent_label_identifier("sd2si_out_of_range")
    cdef AsmOperand dst = generate_operand(node.dst)
    cdef AssemblyType assembly_type_si = QuadWord()
    cdef TIdentifier target_after = represent_label_identifier("sd2si_after")
    cdef AsmOperand dst_out_of_range_sd = generate_register(REGISTER_KIND.get('Xmm1'))
    cdef AsmBinaryOp binary_op_out_of_range_sd_sub = AsmSub()
    cdef AsmOperand upper_bound_si = AsmImm(TIdentifier("9223372036854775808"), True)
    cdef AsmOperand src_out_of_range_si = generate_register(REGISTER_KIND.get('Dx'))
    cdef AsmBinaryOp binary_op_out_of_range_si_add = AsmAdd()
    instructions.append(AsmCmp(assembly_type_sd, upper_bound_sd, src))
    instructions.append(AsmJmpCC(cond_code_ae, target_out_of_range))
    instructions.append(AsmCvttsd2si(assembly_type_si, src, dst))
    instructions.append(AsmJmp(target_after))
    instructions.append(AsmLabel(target_out_of_range))
    instructions.append(AsmMov(assembly_type_sd, src, dst_out_of_range_sd))
    instructions.append(AsmBinary(binary_op_out_of_range_sd_sub, assembly_type_sd, upper_bound_sd, dst_out_of_range_sd))
    instructions.append(AsmCvttsd2si(assembly_type_si, dst_out_of_range_sd, dst))
    instructions.append(AsmMov(assembly_type_si, upper_bound_si, src_out_of_range_si))
    instructions.append(AsmBinary(binary_op_out_of_range_si_add, assembly_type_si, src_out_of_range_si, dst))
    instructions.append(AsmLabel(target_after))