~Ast() {}
CConstInt(TInt value)
CConstLong(TLong value)
CConstUInt(TUInt value)
CConstULong(TULong value)
CConstDouble(TDouble value)
CConstChar(TChar value)
CConstUChar(TUChar value)
CStringLiteral(std::vector<TChar> value)
