#!/bin/python3

class TIdentifier: name = "TIdentifier"
class TChar: name = "TChar"
class TInt: name = "TInt"
class TLong: name = "TLong"
class TUChar: name = "TUChar"
class TUInt: name = "TUInt"
class TULong: name = "TULong"
class TDouble: name = "TDouble"
class Bool: name = "Bool"

ast = [

    # /ast/ast
    ["CConst", [], []],
    ["CConstInt", [(TInt, "value")], []],
    ["CConstLong", [(TLong, "value")], []],
    ["CConstUInt", [(TUInt, "value")], []],
    ["CConstULong", [(TULong, "value")], []],
    ["CConstDouble", [(TDouble, "value")], []],
    ["CConstChar", [(TChar, "value")], []],
    ["CConstUChar", [(TUChar, "value")], []],
    ["CStringLiteral", [(TChar, "[value")], []],

    # /ast/front_symt
    ["Type", [], []],
    ["Char", [], []],
    ["SChar", [], []],
    ["UChar", [], []],
    ["Int", [], []],
    ["Long", [], []],
    ["UInt", [], []],
    ["ULong", [], []],
    ["Double", [], []],
    ["Void", [], []],
    ["FunType", [(TULong, "param_reg_mask"), (TULong, "ret_reg_mask")], ["[param_types", "ret_type"]],
    ["Pointer", [], ["ref_type"]],
    ["Array", [(TLong, "size")], ["elem_type"]],
    ["Structure", [(TIdentifier, "tag"), (Bool, "is_union")], []],
    ["StaticInit", [], []],
    ["IntInit", [(TInt, "value")], []],
    ["LongInit", [(TLong, "value")], []],
    ["UIntInit", [(TUInt, "value")], []],
    ["ULongInit", [(TULong, "value")], []],
    ["CharInit", [(TChar, "value")], []],
    ["UCharInit", [(TUChar, "value")], []],
    ["DoubleInit", [(TIdentifier, "dbl_const")], []],
    ["ZeroInit", [(TLong, "byte")], []],
    ["StringInit", [(TIdentifier, "string_const"), (Bool, "is_null_term")], ["literal"]],
    ["PointerInit", [(TIdentifier, "name")], []],
    ["InitialValue", [], []],
    ["Tentative", [], []],
    ["Initial", [], ["[static_inits"]],
    ["NoInitializer", [], []],
    ["IdentifierAttr", [], []],
    ["FunAttr", [(Bool, "is_def"), (Bool, "is_glob")], []],
    ["StaticAttr", [(Bool, "is_glob")], ["init"]],
    ["ConstantAttr", [], ["static_init"]],
    ["LocalAttr", [], []],
    ["Symbol", [], ["type_t", "attrs"]],
    ["StructMember", [(TLong, "offset")], ["member_type"]],
    ["StructTypedef", [(TInt, "alignment"), (TLong, "size"), (TIdentifier, "[member_names")], ["(members"]],

    # /ast/back_symt
    ["AssemblyType", [], []],
    ["Byte", [], []],
    ["LongWord", [], []],
    ["QuadWord", [], []],
    ["BackendDouble", [], []],
    ["ByteArray", [(TLong, "size"), (TInt, "alignment")], []],
    ["BackendSymbol", [], []],
    ["BackendObj", [(Bool, "is_static"), (Bool, "is_const")], ["asm_type"]],
    ["BackendFun", [(Bool, "is_def")], ["[callee_saved_registers"]],

    # /ast/front_ast
    ["CUnaryOp", [], []],
    ["CComplement", [], []],
    ["CNegate", [], []],
    ["CNot", [], []],
    ["CPrefix", [], []],
    ["CPostfix", [], []],
    ["CBinaryOp", [], []],
    ["CAdd", [], []],
    ["CSubtract", [], []],
    ["CMultiply", [], []],
    ["CDivide", [], []],
    ["CRemainder", [], []],
    ["CBitAnd", [], []],
    ["CBitOr", [], []],
    ["CBitXor", [], []],
    ["CBitShiftLeft", [], []],
    ["CBitShiftRight", [], []],
    ["CBitShrArithmetic", [], []],
    ["CAnd", [], []],
    ["COr", [], []],
    ["CEqual", [], []],
    ["CNotEqual", [], []],
    ["CLessThan", [], []],
    ["CLessOrEqual", [], []],
    ["CGreaterThan", [], []],
    ["CGreaterOrEqual", [], []],
    ["CAbstractDeclarator", [], []],
    ["CAbstractPointer", [], ["abstract_decltor"]],
    ["CAbstractArray", [(TLong, "size")], ["abstract_decltor"]],
    ["CAbstractBase", [], []],
    ["CParam", [], ["decltor", "param_type"]],
    ["CDeclarator", [], []],
    ["CIdent", [(TIdentifier, "name")], []],
    ["CPointerDeclarator", [], ["decltor"]],
    ["CArrayDeclarator", [(TLong, "size")], ["decltor"]],
    ["CFunDeclarator", [], ["[param_list", "decltor"]],
    ["CExp", [], ["exp_type"]],
    ["CConstant", [], ["constant", "exp_type"]],
    ["CString", [], ["literal", "exp_type"]],
    ["CVar", [(TIdentifier, "name")], ["exp_type"]],
    ["CCast", [], ["exp", "target_type", "exp_type"]],
    ["CUnary", [], ["unop", "exp", "exp_type"]],
    ["CBinary", [], ["binop", "exp_left", "exp_right", "exp_type"]],
    ["CAssignment", [], ["unop", "exp_left", "exp_right", "exp_type"]],
    ["CConditional", [], ["condition", "exp_middle", "exp_right", "exp_type"]],
    ["CFunctionCall", [(TIdentifier, "name")], ["[args", "exp_type"]],
    ["CDereference", [], ["exp", "exp_type"]],
    ["CAddrOf", [], ["exp", "exp_type"]],
    ["CSubscript", [], ["primary_exp", "subscript_exp", "exp_type"]],
    ["CSizeOf", [], ["exp", "exp_type"]],
    ["CSizeOfT", [], ["target_type", "exp_type"]],
    ["CDot", [(TIdentifier, "member")], ["structure", "exp_type"]],
    ["CArrow", [(TIdentifier, "member")], ["pointer", "exp_type"]],
    ["CStatement", [], []],
    ["CReturn", [], ["exp"]],
    ["CExpression", [], ["exp"]],
    ["CIf", [], ["condition", "then", "else_fi"]],
    ["CGoto", [(TIdentifier, "target")], []],
    ["CLabel", [(TIdentifier, "target")], ["jump_to"]],
    ["CCompound", [], ["block"]],
    ["CWhile", [(TIdentifier, "target")], ["condition", "body"]],
    ["CDoWhile", [(TIdentifier, "target")], ["condition", "body"]],
    ["CFor", [(TIdentifier, "target")], ["init", "condition", "post", "body"]],
    ["CSwitch", [(TIdentifier, "target"), (Bool, "is_default")], ["match", "body", "[cases"]],
    ["CCase", [(TIdentifier, "target")], ["value", "jump_to"]],
    ["CDefault", [(TIdentifier, "target")], ["jump_to"]],
    ["CBreak", [(TIdentifier, "target")], []],
    ["CContinue", [(TIdentifier, "target")], []],
    ["CNull", [], []],
    ["CForInit", [], []],
    ["CInitDecl", [], ["init"]],
    ["CInitExp", [], ["init"]],
    ["CBlock", [], []],
    ["CB", [], ["[block_items"]],
    ["CBlockItem", [], []],
    ["CS", [], ["statement"]],
    ["CD", [], ["declaration"]],
    ["CStorageClass", [], []],
    ["CStatic", [], []],
    ["CExtern", [], []],
    ["CInitializer", [], ["init_type"]],
    ["CSingleInit", [], ["exp", "init_type"]],
    ["CCompoundInit", [], ["[initializers", "init_type"]],
    ["CMemberDeclaration", [(TIdentifier, "member_name")], ["member_type"]],
    ["CStructDeclaration", [(TIdentifier, "tag"), (Bool, "is_union")], ["[members"]],
    ["CFunctionDeclaration", [(TIdentifier, "name"), (TIdentifier, "[params")], ["body", "fun_type", "storage_class"]],
    ["CVariableDeclaration", [(TIdentifier, "name")], ["init", "var_type", "storage_class"]],
    ["CDeclaration", [], []],
    ["CFunDecl", [], ["fun_decl"]],
    ["CVarDecl", [], ["var_decl"]],
    ["CStructDecl", [], ["struct_decl"]],
    ["CProgram", [], ["[declarations"]],

    # /ast/interm_ast
    ["TacUnaryOp", [], []],
    ["TacComplement", [], []],
    ["TacNegate", [], []],
    ["TacNot", [], []],
    ["TacBinaryOp", [], []],
    ["TacAdd", [], []],
    ["TacSubtract", [], []],
    ["TacMultiply", [], []],
    ["TacDivide", [], []],
    ["TacRemainder", [], []],
    ["TacBitAnd", [], []],
    ["TacBitOr", [], []],
    ["TacBitXor", [], []],
    ["TacBitShiftLeft", [], []],
    ["TacBitShiftRight", [], []],
    ["TacBitShrArithmetic", [], []],
    ["TacEqual", [], []],
    ["TacNotEqual", [], []],
    ["TacLessThan", [], []],
    ["TacLessOrEqual", [], []],
    ["TacGreaterThan", [], []],
    ["TacGreaterOrEqual", [], []],
    ["TacValue", [], []],
    ["TacConstant", [], ["constant"]],
    ["TacVariable", [(TIdentifier, "name")], []],
    ["TacExpResult", [], []],
    ["TacPlainOperand", [], ["val"]],
    ["TacDereferencedPointer", [], ["val"]],
    ["TacSubObject", [(TIdentifier, "base_name"), (TLong, "offset")], []],
    ["TacInstruction", [], []],
    ["TacReturn", [], ["val"]],
    ["TacSignExtend", [], ["src", "dst"]],
    ["TacTruncate", [], ["src", "dst"]],
    ["TacZeroExtend", [], ["src", "dst"]],
    ["TacDoubleToInt", [], ["src", "dst"]],
    ["TacDoubleToUInt", [], ["src", "dst"]],
    ["TacIntToDouble", [], ["src", "dst"]],
    ["TacUIntToDouble", [], ["src", "dst"]],
    ["TacFunCall", [(TIdentifier, "name")], ["[args", "dst"]],
    ["TacUnary", [], ["unop", "src", "dst"]],
    ["TacBinary", [], ["binop", "src1", "src2", "dst"]],
    ["TacCopy", [], ["src", "dst"]],
    ["TacGetAddress", [], ["src", "dst"]],
    ["TacLoad", [], ["src_ptr", "dst"]],
    ["TacStore", [], ["src", "dst_ptr"]],
    ["TacAddPtr", [(TLong, "scale")], ["src_ptr", "idx", "dst"]],
    ["TacCopyToOffset", [(TIdentifier, "dst_name"), (TLong, "offset")], ["src"]],
    ["TacCopyFromOffset", [(TIdentifier, "src_name"), (TLong, "offset")], ["dst"]],
    ["TacJump", [(TIdentifier, "target")], []],
    ["TacJumpIfZero", [(TIdentifier, "target")], ["condition"]],
    ["TacJumpIfNotZero", [(TIdentifier, "target")], ["condition"]],
    ["TacLabel", [(TIdentifier, "name")], []],
    ["TacTopLevel", [], []],
    ["TacFunction", [(TIdentifier, "name"), (Bool, "is_glob"), (TIdentifier, "[params")], ["[body"]],
    ["TacStaticVariable", [(TIdentifier, "name"), (Bool, "is_glob")], ["static_init_type", "[static_inits"]],
    ["TacStaticConstant", [(TIdentifier, "name")], ["static_init_type", "static_init"]],
    ["TacProgram", [], ["[static_constant_top_levels", "[static_variable_top_levels", "[function_top_levels"]],

    # /ast/back_ast
    ["AsmReg", [], []],
    ["AsmAx", [], []],
    ["AsmBx", [], []],
    ["AsmCx", [], []],
    ["AsmDx", [], []],
    ["AsmDi", [], []],
    ["AsmSi", [], []],
    ["AsmR8", [], []],
    ["AsmR9", [], []],
    ["AsmR10", [], []],
    ["AsmR11", [], []],
    ["AsmR12", [], []],
    ["AsmR13", [], []],
    ["AsmR14", [], []],
    ["AsmR15", [], []],
    ["AsmSp", [], []],
    ["AsmBp", [], []],
    ["AsmXMM0", [], []],
    ["AsmXMM1", [], []],
    ["AsmXMM2", [], []],
    ["AsmXMM3", [], []],
    ["AsmXMM4", [], []],
    ["AsmXMM5", [], []],
    ["AsmXMM6", [], []],
    ["AsmXMM7", [], []],
    ["AsmXMM8", [], []],
    ["AsmXMM9", [], []],
    ["AsmXMM10", [], []],
    ["AsmXMM11", [], []],
    ["AsmXMM12", [], []],
    ["AsmXMM13", [], []],
    ["AsmXMM14", [], []],
    ["AsmXMM15", [], []],
    ["AsmCondCode", [], []],
    ["AsmE", [], []],
    ["AsmNE", [], []],
    ["AsmG", [], []],
    ["AsmGE", [], []],
    ["AsmL", [], []],
    ["AsmLE", [], []],
    ["AsmA", [], []],
    ["AsmAE", [], []],
    ["AsmB", [], []],
    ["AsmBE", [], []],
    ["AsmP", [], []],
    ["AsmOperand", [], []],
    ["AsmImm", [(TULong, "value"), (Bool, "is_byte"), (Bool, "is_quad"), (Bool, "is_neg")], []],
    ["AsmRegister", [], ["reg"]],
    ["AsmPseudo", [(TIdentifier, "name")], []],
    ["AsmMemory", [(TLong, "value")], ["reg"]],
    ["AsmData", [(TIdentifier, "name"), (TLong, "offset")], []],
    ["AsmPseudoMem", [(TIdentifier, "name"), (TLong, "offset")], []],
    ["AsmIndexed", [(TLong, "scale")], ["reg_base", "reg_index"]],
    ["AsmBinaryOp", [], []],
    ["AsmAdd", [], []],
    ["AsmSub", [], []],
    ["AsmMult", [], []],
    ["AsmDivDouble", [], []],
    ["AsmBitAnd", [], []],
    ["AsmBitOr", [], []],
    ["AsmBitXor", [], []],
    ["AsmBitShiftLeft", [], []],
    ["AsmBitShiftRight", [], []],
    ["AsmBitShrArithmetic", [], []],
    ["AsmUnaryOp", [], []],
    ["AsmNot", [], []],
    ["AsmNeg", [], []],
    ["AsmShr", [], []],
    ["AsmInstruction", [], []],
    ["AsmMov", [], ["asm_type", "src", "dst"]],
    ["AsmMovSx", [], ["asm_type_src", "asm_type_dst", "src", "dst"]],
    ["AsmMovZeroExtend", [], ["asm_type_src", "asm_type_dst", "src", "dst"]],
    ["AsmLea", [], ["src", "dst"]],
    ["AsmCvttsd2si", [], ["asm_type", "src", "dst"]],
    ["AsmCvtsi2sd", [], ["asm_type", "src", "dst"]],
    ["AsmUnary", [], ["unop", "asm_type", "dst"]],
    ["AsmBinary", [], ["binop", "asm_type", "src", "dst"]],
    ["AsmCmp", [], ["asm_type", "src", "dst"]],
    ["AsmIdiv", [], ["asm_type", "src"]],
    ["AsmDiv", [], ["asm_type", "src"]],
    ["AsmCdq", [], ["asm_type"]],
    ["AsmJmp", [(TIdentifier, "target")], []],
    ["AsmJmpCC", [(TIdentifier, "target")], ["cond_code"]],
    ["AsmSetCC", [], ["cond_code", "dst"]],
    ["AsmLabel", [(TIdentifier, "name")], []],
    ["AsmPush", [], ["src"]],
    ["AsmPop", [], ["reg"]],
    ["AsmCall", [(TIdentifier, "name")], []],
    ["AsmRet", [], []],
    ["AsmTopLevel", [], []],
    ["AsmFunction", [(TIdentifier, "name"), (Bool, "is_glob"), (Bool, "is_ret_memory")], ["[instructions"]],
    ["AsmStaticVariable", [(TIdentifier, "name"), (TInt, "alignment"), (Bool, "is_glob")], ["[static_inits"]],
    ["AsmStaticConstant", [(TIdentifier, "name"), (TInt, "alignment")], ["static_init"]],
    ["AsmProgram", [], ["[static_constant_top_levels", "[top_levels"]],
]
